create DATABASE VOUCHERS_WEB_DB
GO
USE VOUCHERS_WEB_DB
GO
--SOLO CIUDADES DE BUENOS AIRES YA QUE NO SE ESPECIFICA EN EL ENUNCIADO
create TABLE LOCALIDADES(
ID INT NOT NULL identity(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL
)
GO
create TABLE CLIENTES(
DNI INT NOT NULL PRIMARY KEY CHECK(DNI>0),
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
NROCALLE SMALLINT NOT NULL CHECK(NROCALLE>0),
CALLE VARCHAR(30) NOT NULL,
LOCALIDAD varchar(50) NOT NULL,
TELEFONO INT NOT NULL CHECK(TELEFONO>0),
EMAIL VARCHAR(30) NOT NULL
)
GO

create TABLE PRODUCTOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(30) NOT NULL,

)
GO
CREATE TABLE SORTEOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(30) NULL,
FECHA_INI SMALLDATETIME NOT NULL,
FECHA_FIN SMALLDATETIME NOT NULL,
CHECK(FECHA_FIN>FECHA_INI)
)

GO
create TABLE VOUCHERS(
ID VARCHAR(8) NOT NULL PRIMARY KEY,
FECHA DATETIME NOT NULL,
ACTIVO BIT NOT NULL,
ID_SORTEO INT NOT NULL FOREIGN KEY REFERENCES SORTEOS(ID),
ID_PROD_SELEC INT NULL FOREIGN KEY REFERENCES PRODUCTOS(ID)
)
GO
create TABLE COMPRAS(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(ID),
ID_VOUCHER VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES VOUCHERS(ID),
FECHA DATETIME NOT NULL
)
GO
create TABLE NOCLIENTES(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_COMPRA BIGINT NOT NULL FOREIGN KEY REFERENCES COMPRAS(ID)
)
GO
create TABLE COMPRAS_X_CLIENTE(
ID_COMPRA BIGINT NOT NULL FOREIGN KEY REFERENCES COMPRAS(ID),
ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(DNI),
PRIMARY KEY(ID_COMPRA,ID_CLIENTE)
)
GO
create TABLE PREMIOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(ID),
ID_VOUCHER VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES VOUCHERS(ID),
ACTIVO BIT NOT NULL
)
GO

--VOUCHERS

--SP PARA BUSCAR VOUCHER POR ID
--si el id es igual al de db, esta activo,fue comprado, no fue utilizado antes y esta en el sorteo actual
CREATE PROCEDURE SP_BUSCAR_VOUCHER_X_ID
(
@ID_VOUCHER VARCHAR(8)
)
AS
BEGIN

SELECT V.ID,V.FECHA,V.ACTIVO,V.ID_SORTEO,V.ID_PROD_SELEC FROM VOUCHERS AS V 
INNER JOIN COMPRAS AS C ON V.ID=C.ID_VOUCHER
INNER JOIN SORTEOS AS S ON V.ID_SORTEO=S.ID
WHERE @ID_VOUCHER=V.ID AND V.ACTIVO=1 AND V.FECHA=C.FECHA AND V.FECHA BETWEEN CAST(S.FECHA_INI AS DATETIME) AND CAST(S.FECHA_FIN AS DATETIME)

END

GO

--INSERTA EL ID DEL PRODUCTO SELECCIONADO EN EL VOUCHER GANADOR USADO Y LO DA DE BAJA
CREATE PROCEDURE SP_BAJA_VOUCHER
(@ID_VOUCHER VARCHAR(8),
@ID_PROD INT)
AS
BEGIN

UPDATE VOUCHERS SET ID_PROD_SELEC=@ID_PROD , ACTIVO=0
WHERE ID=@ID_VOUCHER

END

--PRODUCTOS
GO
-- SP PARA LISTAR LOS PRODUCTOS DEL VOUCHER GANADOR
CREATE PROCEDURE SP_LISTAR_PROD_WIN_X_VOUCHER
(
@ID_VOUCHER VARCHAR(8)
)
AS
BEGIN

SELECT P.ID,P.NOMBRE,P.URLIMAGEN FROM PRODUCTOS AS P 
INNER JOIN PREMIOS AS PR ON P.ID=PR.ID_PRODUCTO
WHERE @ID_VOUCHER=PR.ID_VOUCHER

END

GO
--CLIENTES

--CARGAR CLIENTE
--si la localidad no existe, la agrega
alter PROCEDURE SP_CARGAR_CLIENTE
(
@DNI INT,
@NOMBRE VARCHAR(30),
@APELLIDO VARCHAR(30),
@NROCALLE SMALLINT,
@CALLE VARCHAR(30),
@LOCALIDAD VARCHAR(50),
@TELEFONO INT,
@EMAIL VARCHAR(30)
)
AS
BEGIN

INSERT INTO CLIENTES (DNI,NOMBRE,APELLIDO,NROCALLE,CALLE,LOCALIDAD,TELEFONO,EMAIL)
VALUES(@DNI,@NOMBRE,@APELLIDO,@NROCALLE,@CALLE,@LOCALIDAD,@TELEFONO,@EMAIL)

END

GO
--SP PARA SABER SI ESTA REGISTRADO EL CLIENTE
CREATE PROCEDURE SP_VERIFICAR_CLIENTE
(
@DNI INT
)
AS
BEGIN

DECLARE @BIT BIT

SELECT @BIT=0

IF CAST((SELECT DNI FROM CLIENTES WHERE @DNI=DNI) AS BIT )=1
BEGIN
SELECT @BIT=1
END

RETURN @BIT

END

GO
--SP PARA MODIFICAR EL CLIENTE
ALTER PROCEDURE SP_MODIFICAR_CLIENTE
(@DNI INT,
@NOMBRE VARCHAR(30),
@APELLIDO VARCHAR(30),
@NROCALLE SMALLINT,
@CALLE VARCHAR(30),
@LOCALIDAD VARCHAR(50),
@TELEFONO INT,
@EMAIL VARCHAR(30)
)
AS
BEGIN 

UPDATE CLIENTES SET DNI=@DNI,NOMBRE=@NOMBRE,
APELLIDO=@APELLIDO,NROCALLE=@NROCALLE,CALLE=@CALLE,
LOCALIDAD=@LOCALIDAD,TELEFONO=@TELEFONO,EMAIL=@EMAIL
WHERE @DNI=DNI

END

GO
--SP PARA BUSCAR EL CLIENTE POR SU DNI
CREATE PROCEDURE SP_BUSCAR_CLIENTE_X_DNI
(@DNI INT)
AS
BEGIN

SELECT * FROM CLIENTES WHERE @DNI=DNI

END

GO
--SP PARA BUSCAR LOCALIDAD POR ID
create PROCEDURE SP_BUSCAR_LOC_X_CODPOSTAL
(
@ID INT
)AS
BEGIN 
SELECT NOMBRE FROM LOCALIDADES WHERE ID=@ID
END
