CREATE DATABASE VOUCHERS_WEB_DB
USE VOUCHERS_WEB_DB
GO
--SOLO CIUDADES DE BUENOS AIRES YA QUE NO SE ESPECIFICA EN EL ENUNCIADO
CREATE TABLE CIUDADES(
COD_POSTAL INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL
)
GO
CREATE TABLE CLIENTES(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
DNI INT NOT NULL UNIQUE,
NROCALLE SMALLINT NOT NULL,
CALLE VARCHAR(30) NOT NULL,
COD_POSTAL INT NOT NULL FOREIGN KEY REFERENCES CIUDADES(COD_POSTAL)
)
GO
CREATE TABLE PRODUCTOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(30) NOT NULL
)
GO
CREATE TABLE SORTEOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBRE VARCHAR(30) NULL,
FECHA_INI SMALLDATETIME NOT NULL,
FECHA_FIN SMALLDATETIME NOT NULL,
CHECK(FECHA_FIN>FECHA_INI)
)

GO
CREATE TABLE VOUCHERS(
ID VARCHAR(8) NOT NULL PRIMARY KEY,
FECHA DATETIME NOT NULL,
ACTIVO BIT NOT NULL,
ID_SORTEO INT NOT NULL FOREIGN KEY REFERENCES SORTEOS(ID)
)
GO
CREATE TABLE COMPRAS(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(ID),
ID_VOUCHER VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES VOUCHERS(ID),
FECHA DATETIME NOT NULL
)
GO
CREATE TABLE NOCLIENTES(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_COMPRA BIGINT NOT NULL FOREIGN KEY REFERENCES COMPRAS(ID)
)
GO
CREATE TABLE COMPRAS_X_CLIENTE(
ID_COMPRA BIGINT NOT NULL FOREIGN KEY REFERENCES COMPRAS(ID),
ID_CLIENTE BIGINT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID),
PRIMARY KEY(ID_COMPRA,ID_CLIENTE)
)
GO
CREATE TABLE PREMIOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
ID_PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(ID),
ID_VOUCHER VARCHAR(8) NOT NULL FOREIGN KEY REFERENCES VOUCHERS(ID),
ACTIVO BIT NOT NULL
)
GO